### ISSUE TITLE
Works on Windows, but blocks when run in GUI

### ISSUE THREAD

**Issue by skyegecko** [alexaandru/nvim-lspupdate#2]
Hi again :)

I just used this for the first time on Windows, and used it to install all my servers from scratch. While it did work, the GUI window was fully blocked during the installation. When the installs completed, the output in the message area appeared all at once.

It seems that when run in a Windows terminal the blocking isn't a problem.

nvim version: v0.5.0-dev+1012-gfe1ebea33 (latest nightly as of right now)
GUI: Neovide 0.6.0 preview

Also tested it on the pre-shipped nvim-qt GUI, but there the problem does not occur.

Is this an issue with your plugin or with Neovide, do you think?

**Comment by alexaandru** [comment]
Hello :)

Bummer... I'll have to dig into this. I only use `Linux` and only use terminal, no GUI (for running nvim, that is). I'll have to fire up a Windows VM and play with it.

**Comment by skyegecko** [comment]
Maybe Neovide on Linux will show the same problem (Neovide is cross platform).

If you need to me to do any specific testing just let me know.

**Comment by alexaandru** [comment]
```
$ neovide 
Ignored client type property: "methods"
Ignored client type property: "attributes"
INTEL-MESA: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

thread 'main' panicked at 'Could not create surface', src/renderer/rendered_window.rs:40:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

... and this is why I stick to terminal :-) Kitty never told me it could not create a surface... :-)

Now, if I think about it, I do run these sequentially, and the console reflects that (displays them as they are being run). If Neovide does things differently, then perhaps it does some sort of buffering. That would seem consistent with the behavior that the message appear all at once. The commands are definitely NOT run all at once, so "someone" (and it ain't this plugin) is running stuff, gathering output and keeping it for themselves. Not sure what I could do from within the plugin to prevent that...

**Comment by skyegecko** [comment]
That's fine. I'll open an issue with Neovide and find out how things work on their end.

Thank you!

Sent from Nine
________________________________
Van: Alexandru Ungur <notifications@github.com> 
verzonden: vrijdag 29 januari 2021 15:00 
Aan: alexaandru/nvim-lspupdate 
Cc: dutchgecko; Author
Onderwerp: Re: [alexaandru/nvim-lspupdate] Works on Windows, but blocks when run in GUI (#2)

$ neovide 
Ignored client type property: "methods"
Ignored client type property: "attributes"
INTEL-MESA: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

thread 'main' panicked at 'Could not create surface', src/renderer/rendered_window.rs:40:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

... and this is why I stick to terminal :-) Kitty never told me it could not create a surface... :-)
Now, if I think about it, I do run these sequentially, and the console reflects that (displays them as they are being run). If Neovide does things differently, then perhaps it does some sort of buffering. That would seem consistent with the behavior that the message appear all at once. The commands are definitely NOT run all at once, so "someone" (and it ain't this plugin) is running stuff, gathering output and keeping it for themselves. Not sure what I could do from within the plugin to prevent that...

**Comment by alexaandru** [comment]
Thank you, let me know how that works out.

**Comment by alexaandru** [comment]
https://stackoverflow.com/questions/18541636/is-stdin-stdout-stderr-buffered-or-unbuffered-in-lua

Maybe it could have something to do with Lua after all. I've played with it a bit more (tried `print()`, `io.write()`) but only managed to make things worse so far: managed to get the above mentioned behaviour (all messages appear at once) also in console :) and with io.write() and unbuffered, I only got partial messages, they got chopped badly :)

So looks like using Vim's `echomsg` (via `vim.cmd()`) is our best bet after all.

**Comment by alexaandru** [comment]
Using `jobstart()` now to run updates async. This should no longer be an issue any longer (untested though, on Windows).
